language: node_js

node_js:
  - stable

services:
  - docker

before_install:
  - docker pull neo4j
  - docker run --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=neo4j/password --volume=$HOME/neo4j/data:/data -d neo4j 

sudo: false

install:
  - yarn install

script:
  - yarn test